/**
 *@fileoverview Serve as a email sender utlity
 */

export async function sendAlertEmail(to: string, deviceId: string, API_KEY?: string) {

  if (!API_KEY) {
    sendMockEmail(to, deviceId)
    return
  }

  try {
     const response = await fetch('https://api.resend.com/emails', {
       method: 'POST',
       headers: {
         'Content-Type': 'application/json',
         'Authorization': `Bearer ${API_KEY}`
       },
       body: JSON.stringify({
         from: 'alerts@amihere.tech',
         to: to,
         subject: `URGENT: Device ${deviceId} is DOWN`,
         html: generateAlertEmailHtml(deviceId)
       })
     });

     if (!response.ok) {
       console.error("Failed to send email API request:", await response.text());
       return
     }
     console.log("email sent to")
   } catch (error) {
      console.error("Error sending email:", error);
   }
 }

async function sendMockEmail(to: string, deviceId: string) {
     console.log(`\n=============================================`);
     console.log(`✉️ MOCK EMAIL DISPATCHED`);
     console.log(`To: ${to}`);
     console.log(`Subject: URGENT: Device ${deviceId} is DOWN`);
     console.log(`Body (HTML length): ${generateAlertEmailHtml(deviceId).length} characters rendered.`);
     console.log(`=============================================\n`);
}


function generateAlertEmailHtml(deviceId: string): string {
   const failureTime = new Date().toUTCString();

   return `
     <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
       <!-- Header -->
       <div style="background-color: #d32f2f; color: white; padding: 20px; text-align: center;">
         <h2 style="margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 1px;">
          Critical Alert
         </h2>
       </div>

       <!-- Body -->
       <div style="padding: 30px; background-color: #ffffff; color: #333333;">
         <p style="font-size: 16px; line-height: 1.6; margin-top: 0;">Hello Support Team,</p>
         <p style="font-size: 16px; line-height: 1.6;">
           The Watchdog Sentinel has detected that a monitored device has stopped sending an active heartbeat. It is now classified as offline.
         </p>

         <!-- Data Box -->
         <div style="background-color: #f9f9f9; border-left: 4px solid #d32f2f; padding: 15px; margin: 25px 0;">
           <p style="margin: 8px 0; font-size: 15px;">
             <strong>Device ID:</strong>
             <span style="font-family: monospace; background: #e0e0e0; padding: 3px 6px; border-radius: 4px; color: #d32f2f;">
               ${deviceId}
             </span>
           </p>
           <p style="margin: 8px 0; font-size: 15px;">
             <strong>Time of Failure:</strong> ${failureTime}
           </p>
           <p style="margin: 8px 0; font-size: 15px;">
             <strong>Status:</strong> <span style="color: #d32f2f; font-weight: bold;">DOWN</span>
           </p>
         </div>

         <p style="font-size: 14px; color: #555555; line-height: 1.5;">
           Please check the device logs immediately or dispatch a maintenance technician to the region.
         </p>
       </div>

       <!-- Footer -->
       <div style="background-color: #f1f5f9; padding: 15px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0;">
         <p style="margin: 0;">Automated message generated by <strong>CritMon Watchdog API</strong></p>
         <p style="margin: 5px 0 0 0;">Do not reply to this email.</p>
       </div>
     </div>
   `;
 }
